name: Deploy Portfolio

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No dependencies to install."
          fi

      - name: Deploy (placeholder)
        run: echo "Add deployment steps here"
